### ISSUE TITLE
Convert version file to markdown?

### ISSUE THREAD

**Issue by bestekov** [andoroth/malifaux_vassal_module#2]
Not sure if the version history is a vassal-specific file that has to be `.txt` but if not, it would probably be better as a `.md`

https://github.com/andoroth/malifaux_vassal_module/blob/ecfe665d4a29d84dcbe01b07f0910611b90ae37b/version%20change%20log.txt#L2

**Comment by andoroth** [comment]
So _that's_ what that file extension is for.

Nope, this is just hand generated - converting everything over to markdown now.  At some point I'll look up markdown syntax and reformat.
